# Generated by Django 3.2.4 on 2021-06-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capeteesstock', '0002_auto_20210608_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='newitem',
            name='stockorder',
            field=models.CharField(choices=[('NEED TO ORDER', 'NEED TO ORDER'), ('ORDERED', 'ORDERED')], default='', max_length=20),
        ),
    ]
