# Generated by Django 3.2.4 on 2021-06-09 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Capeteesstock', '0003_newitem_stockorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newitem',
            name='stockorder',
        ),
    ]
