# Generated by Django 3.2.4 on 2021-06-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Capeteesstock', '0004_remove_newitem_stockorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='newitem',
            name='stockorder',
            field=models.CharField(default='', max_length=20),
        ),
    ]
